[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "binance>=0.3.3",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "ta>=0.11.0",
]
